import type { Metadata } from "next";
import { Sofia_Sans } from "next/font/google";
import "./globals.css";

export const sofia = Sofia_Sans({
  subsets: ["latin"],
  variable: "--font-sofia",
});

export const metadata: Metadata = {
  title: "Countries API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${sofia.variable} font-sans text-lg`}>{children}</body>
    </html>
  );
}
