import type { Metadata } from "next";
import { Sofia_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./../styles/globals.css";
import PageHeader from "@/components/page-header";

const sofia = Sofia_Sans({
  subsets: ["latin"],
  variable: "--font-sofia",
});

export const metadata: Metadata = {
  title: "Countries API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${sofia.variable} font-sans text-lg`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <PageHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
